AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ExpressApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE,PATCH'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        MaxAge: "'86400'"

  ExpressFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs18.x
      MemorySize: 256  
      Timeout: 300 
      Environment:
        Variables:
          MONGODB_URI: "mongodb+srv://admin:qwer1234@jason-cluster.jgdfw.mongodb.net/assets-finance-platform?retryWrites=true&w=majority&appName=jason-cluster"
      Events:
        ApiReadApps:
          Type: Api
          Properties:
            RestApiId: !Ref ExpressApi
            Path: /read-apps
            Method: get
        ApiCreateApps:
          Type: Api
          Properties:
            RestApiId: !Ref ExpressApi
            Path: /create-apps
            Method: post
        ApiDeleteApps:
          Type: Api
          Properties:
            RestApiId: !Ref ExpressApi
            Path: /delete-apps
            Method: delete
        ApiUpdateApps:
          Type: Api
          Properties:
            RestApiId: !Ref ExpressApi
            Path: /update-apps
            Method: put
        ApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ExpressApi
            Path: /
            Method: get

Outputs:
  ApiGatewayInvokeURL:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ExpressApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
